# Generated by Django 5.0 on 2024-02-17 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=64)),
                ('details', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2048)),
                ('style', models.CharField(max_length=64)),
                ('IsBold', models.BooleanField(default=False)),
                ('IsItalic', models.BooleanField(default=False)),
                ('IsUnderline', models.BooleanField(default=False)),
                ('align', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('lastModified', models.DateTimeField()),
                ('collabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collabs', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('medialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MediaOfNote', to='note.media')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TextOfNote', to='note.text')),
            ],
        ),
    ]
