# Generated by Django 5.0 on 2024-02-17 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContentOfTemp', to='note.text')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreatorOfTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
