# Generated by Django 5.0 on 2024-02-17 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShapeType', models.CharField(max_length=64)),
                ('cord1', models.FloatField()),
                ('cord2', models.FloatField()),
                ('Text', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('lastModified', models.DateTimeField()),
                ('collabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collabsOfDiagram', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreatorOfDiagram', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShapesOfDiagram', to='diagram.shape')),
            ],
        ),
    ]
